### ISSUE TITLE
Feature Request: Return to Menu

### ISSUE THREAD

**Issue by Dover8** [BlackDragonBE/MarkdownToRWHTMLUnity#1]
Once you are in a section of the app there is no option in the interface to return to the menu.

![Markdown_To_RW_HTML_Unity_2QKKPTX7Rk](https://user-images.githubusercontent.com/2674965/68867337-8ebd2e00-06ed-11ea-82c6-30fb98842e94.png)

Pressing `Esc` works, but this isn't obvious or documented.

**Comment by BlackDragonBE** [comment]
Thanks Ben, I've merged your pull request to master, but I still need to make and publish new builds for the different platforms. I'll do that ASAP.

**Comment by BlackDragonBE** [comment]
Will be included in version 1.9.

**Comment by BlackDragonBE** [comment]
Included in v1.9.
